[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slamrs-message = { path = "../../slamrs-message" }
embedded-hal-nb = "1.0"
nb = "1.1"
defmt = { version = "0.3", optional = true }
portable-atomic = { version = "1", features = ["critical-section"] }


[features]
defmt = ["dep:defmt", "slamrs-message/defmt"]

