
settings:
  headless: false

nodes:

- !MousePosition

# - !ShapeTest

# - !FileLoader
#   topic_observation: "robot/observation"
#   topic_pose: "robot/pose"

- !Splitter
  splits:
  - !ScannerOdometry
    input: "robot/observation_odometry"
    scanner: "robot/observation"
    odometry: "robot/odometry"
  

- !Simulator
  running: true
  topic_observation_scanner: "robot/observation_odometry"
  topic_command: "robot/command"

  parameters:
    wheel_base: 0.1
    update_period: 0.2
    scanner_range: 1.0

  scene:
  - !Rectangle {x: -1.0, y: -1.0, width: 2.0, height: 2.0}
  - !Rectangle {x: -0.1, y: -0.4, width: 0.5, height: 0.1}
  - !Rectangle {x: -0.6, y:  0.4, width: 0.2, height: 0.5}
  - !Line {x1: -0.6, y1: -0.4, x2: 0.2, y2: 0.4}

- !Controls
  topic_command: "robot/command"
  keyboard_enabled: true
  max_speed: 0.1

- !IcpPointMapper
  topic_observation: "robot/observation"
  topic_pose: "robot/pose"
  topic_pointmap: "slam/map"
  icp:
    iterations: 10
    correspondence_weights: !Step {threshold: 0.05}

- !Visualizer
  topics:
  
  - !PointMap
    topic: "slam/map"
    config:
      size: 0.01
      point_color: [0.0, 1.0, 0.0]
    
  - !Observation
    topic: "robot/observation"
    topic_pose: "robot/pose"
    config:
      draw_lines: true
      size: 0.01
      point_color: [0.0, 1.0, 0.0]

  - !Pose
    topic: "robot/pose"
    config:
      color: [0.0, 1.0, 1.0]
      radius: 0.1
        
