settings:
  headless: false

nodes:

- !MousePosition

- !Splitter
  splits:
  - !LandmarkOdometry
    input: "robot/observation_odometry"
    landmark: "robot/landmarks"
    odometry: "robot/odometry"

- !Simulator
  running: true
  topic_observation_landmarks: "robot/observation_odometry"
  topic_pose: "simulator/pose"
  topic_command: "robot/command"

  parameters:
    wheel_base: 0.1
    update_period: 0.2
    scanner_range: 1.0

  landmarks:
  - !Landmark {x: -1.0, y: -1.0}
  - !Landmark {x:  1.0, y:  1.0}
  - !Landmark {x: -0.1, y: -0.4}
  - !Landmark {x: -0.6, y:  0.4}
  - !Landmark {x: -0.6, y: -0.4}
  - !Landmark {x:  0.6, y:  0.4}
  - !Landmark {x:  0.6, y: -0.4}


- !Controls
  topic_command: "robot/command"
  keyboard_enabled: true
  max_speed: 0.1


- !Visualizer
  topics:
  
  # - !PointMap
  #   topic: "slam/map"
  #   config:
  #     size: 0.01
  #     point_color: [0.0, 1.0, 0.0]
    
  - !LandmarkObservation
    topic: "robot/landmarks"
    topic_pose: "simulator/pose"
    config:
      
  - !LandmarkMap
    topic: "slam/map"
    config:
      
  - !Pose
    topic: "slam/pose"
    config:
      color: [0.0, 1.0, 1.0]
      radius: 0.1
        
- !EKFLandmarkSlam
  topic_observation_landmark: "robot/observation_odometry"
  topic_pose: "slam/pose"
  topic_map: "slam/map"
  config:
