settings:
  headless: false

nodes:

- !MousePosition

- !Splitter
  splits:
  - !LandmarkOdometry
    input: "extraction/landmarks_odometry"
    landmark: "robot/landmarks"
    odometry: "robot/odometry"
  - !ScannerOdometry
    input: "robot/observation_odometry"
    scanner: "robot/observation"
    odometry: "robot/odometry"

- !Simulator
  running: true
  topic_observation_scanner: "robot/observation_odometry"
  topic_pose: "simulator/pose"
  topic_command: "robot/command"

  parameters:
    wheel_base: 0.1
    update_period: 0.2
    scanner_range: 1.0

  scene:
  - !Rectangle {x: -1.0, y: -1.0, width: 2.0, height: 2.0}
  - !Rectangle {x: -0.1, y: -0.4, width: 0.5, height: 0.1}
  - !Rectangle {x: -0.6, y:  0.4, width: 0.2, height: 0.5}
  - !Line {x1: -0.6, y1: -0.4, x2: 0.2, y2: 0.4}

- !Controls
  topic_command: "robot/command"
  keyboard_enabled: true
  max_speed: 0.1

- !LandmarkExtraction
    topic_in_scan_odometry: "robot/observation_odometry"
    topic_out_landmarks_odometry: "extraction/landmarks_odometry"

- !Visualizer
  topics:
  
  # - !PointMap
  #   topic: "slam/map"
  #   config:
  #     size: 0.01
  #     point_color: [0.0, 1.0, 0.0]
  - !Observation
    topic: "robot/observation"
    topic_pose: "simulator/pose"
    config:
      draw_lines: false
      size: 0.01
      point_color: [0.0, 1.0, 0.0]

  - !LandmarkObservation
    topic: "robot/landmarks"
    topic_pose: "simulator/pose"
    config:
      
  - !LandmarkMap
    topic: "slam/map"
    config:
      
  - !Pose
    topic: "slam/pose"
    config:
      color: [0.0, 1.0, 1.0]
      radius: 0.1
        
# - !EKFLandmarkSlam
#   topic_observation_landmark: "extraction/landmarks"
#   topic_pose: "slam/pose"
#   topic_map: "slam/map"
#   config:
