
settings:
  headless: false

nodes:

- !MousePosition


- !Controls
  topic_command: "robot/command"
  keyboard_enabled: true
  max_speed: 0.1

- !GridMapSlam
  topic_observation: "robot/observation"
  topic_pose: "robot/pose"
  topic_map: "slam/map"
  config:
    position: [-3.0, -3.0]
    width: 6.0
    height: 6.0
    resolution: 0.05


- !Visualizer
  topics:
  
  - !GridMap
    topic: "slam/map"
    config:
      gridlines: false
    
  - !Observation
    topic: "robot/observation"
    topic_pose: "robot/pose"
    config:
      draw_lines: true
      size: 0.01
      point_color: [0.0, 1.0, 0.0]

  - !Pose
    topic: "robot/pose"
    config:
      color: [0.0, 1.0, 1.0]
      radius: 0.1



- !Simulator
  running: true
  topic_observation: "robot/observation"
  topic_pose: "robot/pose"
  topic_command: "robot/command"

  parameters:
    wheel_base: 0.1
    update_period: 0.2

  scene:
  - !Rectangle {x: -1.0, y: -1.0, width: 2.0, height: 2.0}
  - !Rectangle {x: -0.1, y: -0.4, width: 0.5, height: 0.1}
  - !Rectangle {x: -0.6, y:  0.4, width: 0.2, height: 0.5}
  - !Line {x1: -0.6, y1: -0.4, x2: 0.2, y2: 0.4}
