
settings:
  headless: false

nodes:

- !MousePosition

# - !ShapeTest

- !SerialConnection
  topic_observation: "robot/observation"

- !FileLoader
  topic_observation: "robot/observation"
  topic_pose: "robot/pose"
  
- !Controls
  topic_command: "robot/command"
  keyboard_enabled: true
  max_speed: 0.1

- !IcpPointMapper
  topic_observation: "robot/observation"
  topic_pose: "robot/pose"
  topic_pointmap: "slam/map"
  icp:
    iterations: 10
    correspondence_weights: !Step {threshold: 0.05}

- !Visualizer
  topics:
  
  - !PointMap
    topic: "slam/map"
    config:
      size: 0.01
      point_color: [0.0, 1.0, 0.0]
    
  - !Observation
    topic: "robot/observation"
    topic_pose: "robot/pose"
    config:
      draw_lines: true
      size: 0.01
      point_color: [0.0, 1.0, 0.0]

  - !Pose
    topic: "robot/pose"
    config:
      color: [0.0, 1.0, 1.0]
      radius: 0.1

  


#   scanner:
#     rate: 5
#     fov: 360

# - IcpPointMapper
#   icp_threshold: 300

        
