on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
name: "Build: slamrs-robot" 


# Since `espup` queries the GitHub API, we strongly recommend you provide this
# action with an API token to avoid transient errors.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # needed by the code for compilation since the Wifi details are baked into the binary
  SSID: DUMMY_SSID
  PASSWORD: DUMMY_PASSWORD

  
# all the run steps should execute in the subfolder
defaults:
  run:
    working-directory: ./slamrs-robot

jobs:
  build_robot:
    name: Build robot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: "esp32"
          version: "latest"
          ldproxy: true

      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./slamrs-robot -> target"

      # `cargo check` command here will use installed `esp` toolchain, as it
      # has been set as the default above

      - name: Check
        run: cargo check

      - name: Build
        run: cargo build